apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
